.TH FOO 1 "January 11 2014"
.SH NAME
FOO \- Action platformer built in LOVE.
.SH SYNOPSIS
.B foo
.SH DESCRIPTION
This manual page documents briefly the
.B foo
command.
.PP
\fBfoo\fP is a graphical action platform built using Lua and the LOVE framework.
.SH OPTIONS
This command executes a
.BR sh (1)
script of the foo.love package against the love executable.
.SH SEE ALSO
.BR love (1)
.br
.SH AUTHOR
foo was written by FooBar Games.