InputMap = {
    x = "u",
    y = "i",
    up = "up",
    lk5 = "end",
    lk1 = "home",
    left = "left",
    down = "down",
    lk2 = "pageup",
    lk3 = "lshift",
    right = "right",
    menu = "escape",
    select = "space",
    lk4 = "pagedown",
    start = "kpenter",
    a = love.system.getOS() == "Linux" and "j" or "z",
    b = love.system.getOS() == "Linux" and "k" or "x",
}